# Generated by Django 2.1.5 on 2022-06-15 16:55

import FileApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FolderApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=FileApp.models.get_user_directory)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FolderApp.Folder')),
            ],
        ),
    ]
