# Generated by Django 2.1.5 on 2022-06-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.BigIntegerField()),
            ],
        ),
    ]
