# Generated by Django 2.1.5 on 2022-06-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0006_auto_20220616_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='catogery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FileApp.Catogery'),
        ),
    ]
