# Generated by Django 2.1.5 on 2022-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0007_auto_20220616_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
