# Generated by Django 2.1.5 on 2022-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0008_auto_20220617_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
