# Generated by Django 2.1.5 on 2022-06-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0009_auto_20220617_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
