# Generated by Django 2.1.5 on 2022-06-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='expiry',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
