# Generated by Django 2.1.5 on 2022-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtpApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
