# Generated by Django 2.1.5 on 2022-06-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtpApp', '0003_auto_20220614_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
